/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProsjekterRouteImport } from './routes/prosjekter'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TjenesterIndexRouteImport } from './routes/tjenester.index'
import { Route as TjenesterSlugRouteImport } from './routes/tjenester.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjekterRoute = ProsjekterRouteImport.update({
  id: '/prosjekter',
  path: '/prosjekter',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjenesterIndexRoute = TjenesterIndexRouteImport.update({
  id: '/tjenester/',
  path: '/tjenester/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjenesterSlugRoute = TjenesterSlugRouteImport.update({
  id: '/tjenester/$slug',
  path: '/tjenester/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/prosjekter': typeof ProsjekterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjenester/$slug': typeof TjenesterSlugRoute
  '/tjenester/': typeof TjenesterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/prosjekter': typeof ProsjekterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjenester/$slug': typeof TjenesterSlugRoute
  '/tjenester': typeof TjenesterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/karriere': typeof KarriereRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/prosjekter': typeof ProsjekterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjenester/$slug': typeof TjenesterSlugRoute
  '/tjenester/': typeof TjenesterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/karriere'
    | '/kontakt'
    | '/om-oss'
    | '/prosjekter'
    | '/sitemap.xml'
    | '/tjenester/$slug'
    | '/tjenester/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/karriere'
    | '/kontakt'
    | '/om-oss'
    | '/prosjekter'
    | '/sitemap.xml'
    | '/tjenester/$slug'
    | '/tjenester'
  id:
    | '__root__'
    | '/'
    | '/karriere'
    | '/kontakt'
    | '/om-oss'
    | '/prosjekter'
    | '/sitemap.xml'
    | '/tjenester/$slug'
    | '/tjenester/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KarriereRoute: typeof KarriereRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  ProsjekterRoute: typeof ProsjekterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TjenesterSlugRoute: typeof TjenesterSlugRoute
  TjenesterIndexRoute: typeof TjenesterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekter': {
      id: '/prosjekter'
      path: '/prosjekter'
      fullPath: '/prosjekter'
      preLoaderRoute: typeof ProsjekterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjenester/': {
      id: '/tjenester/'
      path: '/tjenester'
      fullPath: '/tjenester/'
      preLoaderRoute: typeof TjenesterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjenester/$slug': {
      id: '/tjenester/$slug'
      path: '/tjenester/$slug'
      fullPath: '/tjenester/$slug'
      preLoaderRoute: typeof TjenesterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KarriereRoute: KarriereRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  ProsjekterRoute: ProsjekterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TjenesterSlugRoute: TjenesterSlugRoute,
  TjenesterIndexRoute: TjenesterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
